apiVersion: 1
datasources:
- name: Mimir team-a
  type: prometheus
  access: proxy
  uid: mimir-team-a
  orgID: team-a
  url: http://nginx:8080/prometheus
  isDefault: true
  jsonData:
    prometheusType: Mimir
    exemplarTraceIdDestinations:
      - name: traceID
        datasourceUid: jaeger
    httpHeaderName1: 'X-Scope-OrgID'
  secureJsonData:
    httpHeaderValue1: 'team-a'
- name: Mimir team-b
  type: prometheus
  access: proxy
  uid: mimir-team-b
  orgID: team-b
  url: http://nginx:8080/prometheus
  jsonData:
    prometheusType: Mimir
    exemplarTraceIdDestinations:
      - name: traceID
        datasourceUid: jaeger
    httpHeaderName1: 'X-Scope-OrgID'
  secureJsonData:
    httpHeaderValue1: 'team-b'
- name: Jaeger
  type: jaeger
  access: proxy
  uid: jaeger
  orgID: 1
  url: http://jaeger:16686/