name: publish-technical-documentation-release-mimir

on:
  push:
    branches:
      - "release-*"
    tags:
      - "mimir-[0-9]+.[0-9]+.[0-9]+"
    paths:
      - "docs/sources/mimir/**"
  workflow_dispatch:
jobs:
  test:
    uses: ./.github/workflows/test-docs.yml
  sync:
    if: github.repository == 'grafana/mimir'
    needs: test
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: grafana/writers-toolkit/publish-technical-documentation-release@publish-technical-documentation-release/v1
        with:
          release_tag_regexp: "^mimir-(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$"
          release_branch_regexp: "^release-(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$"
          release_branch_with_patch_regexp: "^release-(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)$"
          source_directory: docs/sources/mimir
          website_directory: content/docs/mimir
